"""Closed catalog of Event types accepted by the canonical EventStore."""

from __future__ import annotations

from cogito.domain.event import EventClass, EventValidationError

_TYPES: dict[str, EventClass] = {
    "interaction.message.accepted": EventClass.DOMAIN,
    "interaction.message.recorded": EventClass.DOMAIN,
    "interaction.principal.created": EventClass.DOMAIN,
    "interaction.endpoint.created": EventClass.DOMAIN,
    "interaction.conversation.created": EventClass.DOMAIN,
    "interaction.session.created": EventClass.DOMAIN,
    "runtime.turn.accepted": EventClass.DOMAIN,
    "runtime.turn.queued": EventClass.DOMAIN,
    "runtime.turn.started": EventClass.OPERATION,
    "runtime.turn.completed": EventClass.DOMAIN,
    "runtime.turn.failed": EventClass.DOMAIN,
    "runtime.turn.cancelled": EventClass.DOMAIN,
    "runtime.turn.waiting_user": EventClass.OPERATION,
    "runtime.turn.waiting_external": EventClass.OPERATION,
    "runtime.attempt.started": EventClass.OPERATION,
    "runtime.attempt.completed": EventClass.OPERATION,
    "runtime.attempt.failed": EventClass.OPERATION,
    "runtime.attempt.cancelled": EventClass.OPERATION,
    "runtime.attempt.abandoned": EventClass.OPERATION,
    "runtime.attempt.lease_renewed": EventClass.OPERATION,
    "runtime.checkpoint.saved": EventClass.OPERATION,
    "runtime.checkpoint.invalidated": EventClass.OPERATION,
    "runtime.session.completed": EventClass.DOMAIN,
    "runtime.context.assembled": EventClass.OPERATION,
    "runtime.response.generated": EventClass.OPERATION,
    "model.call.started": EventClass.OPERATION,
    "model.call.completed": EventClass.OPERATION,
    "model.call.failed": EventClass.OPERATION,
    "model.call.cancelled": EventClass.OPERATION,
    "tool.call.requested": EventClass.OPERATION,
    "tool.call.approval_required": EventClass.OPERATION,
    "tool.call.started": EventClass.OPERATION,
    "tool.call.completed": EventClass.OPERATION,
    "tool.call.failed": EventClass.OPERATION,
    "tool.call.cancelled": EventClass.OPERATION,
    "tool.call.unknown": EventClass.OPERATION,
    "side_effect.receipt.recorded": EventClass.DOMAIN,
    "side_effect.receipt.resolved": EventClass.DOMAIN,
    "side_effect.receipt.reconciled": EventClass.DOMAIN,
    "delivery.requested": EventClass.DOMAIN,
    "delivery.started": EventClass.OPERATION,
    "delivery.completed": EventClass.DOMAIN,
    "delivery.failed": EventClass.DOMAIN,
    "delivery.unknown": EventClass.DOMAIN,
    "delivery.cancelled": EventClass.DOMAIN,
    "delivery.retry_scheduled": EventClass.DOMAIN,
    "delivery.retry_requested": EventClass.DOMAIN,
    "task.created": EventClass.DOMAIN,
    "task.scheduled": EventClass.DOMAIN,
    "task.leased": EventClass.OPERATION,
    "task.lease_renewed": EventClass.OPERATION,
    "task.attempt.started": EventClass.OPERATION,
    "task.attempt.completed": EventClass.OPERATION,
    "task.attempt.failed": EventClass.OPERATION,
    "task.attempt.cancelled": EventClass.OPERATION,
    "task.attempt.abandoned": EventClass.OPERATION,
    "task.waiting_user": EventClass.OPERATION,
    "task.waiting_external": EventClass.OPERATION,
    "task.retry_scheduled": EventClass.DOMAIN,
    "task.completed": EventClass.DOMAIN,
    "task.failed": EventClass.DOMAIN,
    "task.cancelled": EventClass.DOMAIN,
    "drift.checkpoint.saved": EventClass.OPERATION,
    "schedule.created": EventClass.DOMAIN,
    "schedule.fired": EventClass.OPERATION,
    "schedule.enabled_toggled": EventClass.OPERATION,
    "drift.preemption.requested": EventClass.OPERATION,
    "drift.preemption.consumed": EventClass.OPERATION,
    "delegation.created": EventClass.DOMAIN,
    "delegation.completed": EventClass.DOMAIN,
    "delegation.cancelled": EventClass.DOMAIN,
    "delegation.child.completed": EventClass.OPERATION,
    "connector.created": EventClass.DOMAIN,
    "connector.status.updated": EventClass.DOMAIN,
    "connector.cursor.updated": EventClass.OPERATION,
    "connector.source.ingested": EventClass.DOMAIN,
    "memory.extraction.requested": EventClass.DOMAIN,
    "memory.signal.recorded": EventClass.DOMAIN,
    "memory.source.invalidated": EventClass.DOMAIN,
    "memory.weight.recomputed": EventClass.OPERATION,
    "memory.candidate.created": EventClass.DOMAIN,
    "memory.confirmed": EventClass.DOMAIN,
    "memory.rejected": EventClass.DOMAIN,
    "memory.superseded": EventClass.DOMAIN,
    "memory.expired": EventClass.DOMAIN,
    "memory.erased": EventClass.DOMAIN,
    "knowledge.resource.created": EventClass.DOMAIN,
    "knowledge.resource.updated": EventClass.DOMAIN,
    "knowledge.resource.ingested": EventClass.DOMAIN,
    "knowledge.resource.invalidated": EventClass.DOMAIN,
    "knowledge.resource.deleted": EventClass.DOMAIN,
    "knowledge.document.parsed": EventClass.OPERATION,
    "knowledge.document.created": EventClass.DOMAIN,
    "knowledge.segment.created": EventClass.OPERATION,
    "knowledge.embedding.written": EventClass.OPERATION,
    "approval.requested": EventClass.DOMAIN,
    "approval.responded": EventClass.DOMAIN,
    "approval.expired": EventClass.DOMAIN,
    "approval.cancelled": EventClass.DOMAIN,
    "approval.consumed": EventClass.OPERATION,
    "agent.command.completed": EventClass.DOMAIN,
    "proactive.candidate.created": EventClass.DOMAIN,
    "proactive.cadence.evaluated": EventClass.OPERATION,
    "proactive.decision.made": EventClass.DOMAIN,
    "proactive.delivery.requested": EventClass.DOMAIN,
    "proactive.delivery.completed": EventClass.DOMAIN,
    "proactive.delivery.failed": EventClass.DOMAIN,
    "drift.result.committed": EventClass.DOMAIN,
    "drift.run.admitted": EventClass.DOMAIN,
    "drift.run.progress.recorded": EventClass.OPERATION,
    "drift.run.checkpoint.recorded": EventClass.OPERATION,
    "drift.run.paused": EventClass.OPERATION,
    "drift.run.completed": EventClass.DOMAIN,
    "drift.run.failed": EventClass.DOMAIN,
    "drift.run.needs_review": EventClass.DOMAIN,
    "drift.skill_state.updated": EventClass.OPERATION,
    "drift.run.imported": EventClass.TELEMETRY,
    # Canonical terminal snapshots emitted only by the offline legacy importer.
    # They deliberately describe one recoverable final state rather than
    # inventing lifecycle Events that the old schema did not retain.
    "interaction.principal.imported": EventClass.TELEMETRY,
    "interaction.endpoint.imported": EventClass.TELEMETRY,
    "interaction.conversation.imported": EventClass.TELEMETRY,
    "interaction.session.imported": EventClass.TELEMETRY,
    "interaction.message.imported": EventClass.TELEMETRY,
    "runtime.turn.imported": EventClass.TELEMETRY,
    "runtime.attempt.imported": EventClass.TELEMETRY,
    "task.imported": EventClass.TELEMETRY,
    "task.attempt.imported": EventClass.TELEMETRY,
    "model.call.imported": EventClass.TELEMETRY,
    "tool.call.imported": EventClass.TELEMETRY,
    "delivery.imported": EventClass.TELEMETRY,
    "approval.imported": EventClass.TELEMETRY,
    "connector.source.imported": EventClass.TELEMETRY,
    "connector.imported": EventClass.TELEMETRY,
    "connector.cursor.imported": EventClass.TELEMETRY,
    "memory.imported": EventClass.TELEMETRY,
    "knowledge.resource.imported": EventClass.TELEMETRY,
    "proactive.candidate.imported": EventClass.TELEMETRY,
    "proactive.decision.imported": EventClass.TELEMETRY,
    "multimodal.asset.created": EventClass.DOMAIN,
    "multimodal.asset.deleted": EventClass.DOMAIN,
    "multimodal.sticker.marked": EventClass.OPERATION,
    "multimodal.sticker.used": EventClass.OPERATION,
    "vision.analysis.queued": EventClass.OPERATION,
    "vision.analysis.started": EventClass.OPERATION,
    "vision.analysis.completed": EventClass.DOMAIN,
    "vision.analysis.failed": EventClass.DOMAIN,
    "side_effect.receipt.imported": EventClass.TELEMETRY,
    "legacy.principal.imported": EventClass.TELEMETRY,
    "legacy.endpoint.imported": EventClass.TELEMETRY,
    "legacy.conversation.imported": EventClass.TELEMETRY,
    "legacy.session.imported": EventClass.TELEMETRY,
    "legacy.message.imported": EventClass.TELEMETRY,
    "legacy.turn.imported": EventClass.TELEMETRY,
    "legacy.run_attempt.imported": EventClass.TELEMETRY,
    "legacy.task.imported": EventClass.TELEMETRY,
    "legacy.task_attempt.imported": EventClass.TELEMETRY,
    "legacy.model_call.imported": EventClass.TELEMETRY,
    "legacy.tool_call.imported": EventClass.TELEMETRY,
    "legacy.delivery.imported": EventClass.TELEMETRY,
    "legacy.approval.imported": EventClass.TELEMETRY,
    "legacy.connector_item.imported": EventClass.TELEMETRY,
    "legacy.proactive_candidate.imported": EventClass.TELEMETRY,
    "legacy.proactive_decision.imported": EventClass.TELEMETRY,
    "legacy.drift_run.imported": EventClass.TELEMETRY,
    "legacy.memory.imported": EventClass.TELEMETRY,
    "legacy.knowledge_resource.imported": EventClass.TELEMETRY,
    "legacy.snapshot.imported": EventClass.TELEMETRY,
}


def event_class_for(event_type: str) -> EventClass:
    """Return the registered class or reject an unknown event at the boundary."""
    try:
        return _TYPES[event_type]
    except KeyError as exc:
        raise EventValidationError(f"unregistered event type: {event_type}") from exc


def registered_event_types() -> frozenset[str]:
    return frozenset(_TYPES)
