# cogito/agent/domain/approval.py
#
# Domain types for tool-call approval / suspension / checkpoint.
#
# Design rules (see agent-loop-phase-spec §13.2–§13.4):
#   - PendingApprovalBatch captures what needs user consent.
#   - AgentLoopCheckpoint is fully serialisable (no SDK/DB objects).
#   - ApprovalDecisionCommand is Channel-agnostic.
#   - integrity_hash covers actor, session, approval id, call ids + args.

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum
from typing import Mapping

from cogito.agent.domain.messages import ModelMessage
from cogito.agent.domain.tools import ToolCall, ToolCallPlan, ToolRiskLevel, ToolSideEffect
from cogito.agent.domain.usage import UsageSummary


# ── Approval item ───────────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class PendingApprovalItem:
    """One tool call awaiting user approval.

    ``approval_prompt`` is a user-facing description generated by the
    policy layer (e.g. "Send email '…' to alice@example.com").
    """

    call: ToolCall
    tool_name: str
    risk_level: ToolRiskLevel
    side_effect: ToolSideEffect
    reason_code: str
    approval_prompt: str


@dataclass(frozen=True, slots=True)
class PendingApprovalBatch:
    """All tool calls from one model round that need user consent.

    When any item in a round requires approval, the entire batch is
    paused — no tool executes until the user decides on every item.
    """

    approval_id: str
    turn_id: str
    actor_id: str
    session_id: str
    created_at: datetime
    expires_at: datetime | None
    items: tuple[PendingApprovalItem, ...]


# ── Checkpoint ──────────────────────────────────────────────────────────


@dataclass(frozen=True, slots=True)
class AgentLoopCheckpoint:
    """Snapshot of agent-loop state so it can resume after approval.

    Contains everything needed to reconstruct the turn state after a
    user decision.  Does NOT hold:
      - Model SDK objects
      - Exception instances
      - EventSink references
      - Database connections
      - CancellationToken
    """

    original_turn_id: str
    approval_id: str
    model_messages: tuple[ModelMessage, ...]
    tool_plan: ToolCallPlan
    model_calls_used: int
    tool_rounds_used: int
    total_tool_calls_used: int
    usage: UsageSummary
    integrity_hash: str


# ── Approval action / command ───────────────────────────────────────────


class ApprovalAction(StrEnum):
    APPROVE = "approve"
    REJECT = "reject"


@dataclass(frozen=True, slots=True)
class ApprovalDecisionCommand:
    """Channel-agnostic command to resolve a pending approval.

    ``approval_id`` matches a PendingApprovalBatch.
    ``actions`` maps call_id → approve | reject.
    """

    approval_id: str
    actions: Mapping[str, ApprovalAction]
