# cogito/agent/domain/preferences.py
#
# Preference candidate model for knowledge extraction.
#
# Design rules (see initial-framework-spec §6.5, persistence-phase-spec §5.2):
#   - PreferenceCandidate carries extracted preference candidates from
#     KnowledgeExtractionPhase to PersistencePhase.
#   - All fields are frozen/immutable — created once, read many.
#   - candidate_id is required for audit trail and idempotency.
#   - source_refs replaces source_message_id for multi-source support.
#   - source_message_id is kept as a deprecated backward-compat alias.

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum
from typing import Mapping


class CandidateOperation(StrEnum):
    INSERT = "insert"
    UPDATE = "update"
    DELETE = "delete"
    IGNORE = "ignore"
    TENTATIVE = "tentative"


@dataclass(frozen=True, slots=True)
class PreferenceCandidate:
    """Extracted preference candidate from KnowledgeExtractionPhase.

    ``candidate_id`` is a stable identifier generated by the extraction
    phase.  It is used in PersistencePhase for idempotent audit.

    ``content`` is the natural-language description of the preference.

    ``value`` is the parsed value (string, number, boolean, or a JSON
    object).  It can be None for DELETE / IGNORE operations.

    ``source_refs`` is a tuple of stable references (event IDs, span IDs)
    that serve as evidence for this candidate.

    .. deprecated::
        ``source_message_id`` is kept for backward compatibility with
        phase 5 (AgentLoopPhase).  New code should use ``source_refs``.
    """

    key: str
    operation: CandidateOperation
    confidence: float
    candidate_id: str = ""
    value: object | None = None
    content: str = ""
    importance: float = 0.5
    source_refs: tuple[str, ...] = ()
    metadata: Mapping[str, object] = field(default_factory=dict)

    @property
    def source_message_id(self) -> str | None:
        """Deprecated backward-compat alias for single-source refs."""
        if len(self.source_refs) == 1:
            return self.source_refs[0]
        if len(self.source_refs) > 0:
            return self.source_refs[0]
        return None
